### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by madyke** [madyke/SDSMT_Web#3]
Right now, there is an edit button an individual student's webpage. User authentication should be used so that this button is only visible to the student who owns the page and to the system administrator.

**Comment by jaydawgkj** [comment]
There was a problem with the log in function working properly.  I talked with Dan and we hard coded in the log in function always returning true and logging in "User" when an attempt is made. It is not perfect but this shows the button only appearing when this user is logged in.
